@extends('layouts.admin')
@section('title','Rejection Reasons')
@section('admin-content')
<div class="space-y-5 p-5 lg:p-6"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-[10px] font-extrabold uppercase tracking-[.2em] admin-theme-text">Property moderation</p><h1 class="mt-1 text-2xl font-extrabold">Rejection Reasons</h1><p class="text-sm text-slate-500">Reasons shown to admins while rejecting a property listing.</p></div><button type="button" id="addReason" class="rounded-xl admin-theme-bg px-5 py-3 text-sm font-bold text-white"><i class="fas fa-plus mr-2"></i>Add reason</button></div>
<div class="grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border bg-white p-4"><p class="text-[10px] font-bold uppercase text-slate-400">Active reasons</p><p class="mt-1 text-2xl font-extrabold admin-theme-text">{{ $reasons->where('is_active', true)->count() }}</p></div><div class="rounded-2xl border bg-white p-4 sm:col-span-2"><p class="text-sm font-bold">How it works</p><p class="mt-1 text-xs text-slate-500">Admin selects one reason on the Property Listings page. The selected reason is saved against the property and can be included in the owner notification.</p></div></div>
<div class="overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="border-b px-5 py-4"><h2 class="text-sm font-extrabold">Available moderation reasons</h2></div><div class="divide-y">@forelse($reasons as $index=>$reason)<div class="flex items-center gap-4 px-5 py-4 hover:bg-slate-50 {{ !$reason->is_active ? 'bg-slate-50 opacity-75' : '' }}"><div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl admin-theme-soft text-xs font-extrabold admin-theme-text">{{ $index+1 }}</div><p class="min-w-0 flex-1 text-sm font-semibold text-slate-700">{{ $reason->reason }}</p><x-admin.status-toggle :active="$reason->is_active" :action="route('admin.rejection-reasons.toggle-status', $reason)" :data-label="$reason->reason" /><x-admin.action-icon variant="edit" type="button" class="edit-reason" data-id="{{ $reason->id }}" data-reason="{{ $reason->reason }}" /><form method="POST" action="{{ route('admin.rejection-reasons.destroy', $reason) }}" class="admin-confirm" data-confirm-title="Delete this reason?" data-confirm-text="This will hide the reason from future moderation choices." data-confirm-button="Yes, delete">@csrf @method('DELETE')<x-admin.action-icon variant="delete" type="submit" /></form></div>@empty<p class="p-12 text-center text-sm text-slate-500">No rejection reasons.</p>@endforelse</div></div>
<form id="reasonCreateForm" method="POST" action="{{ route('admin.rejection-reasons.store') }}" class="hidden">@csrf<input name="reason"></form><form id="reasonEditForm" method="POST" class="hidden">@csrf @method('PUT')<input name="reason"></form></div>
@endsection
@push('scripts')<script>
const askReason=async(title,value='')=>Swal.fire({title,input:'text',inputValue:value,inputPlaceholder:'Enter a clear rejection reason',showCancelButton:true,confirmButtonText:'Save reason',confirmButtonColor:'#4f46e5',inputAttributes:{maxlength:255},inputValidator:v=>!v?.trim()?'Reason is required.':undefined});
document.getElementById('addReason').addEventListener('click',async()=>{const r=await askReason('Add rejection reason');if(r.isConfirmed){const f=document.getElementById('reasonCreateForm');f.reason.value=r.value.trim();f.submit();}});
document.querySelectorAll('.edit-reason').forEach(b=>b.addEventListener('click',async()=>{const r=await askReason('Edit rejection reason',b.dataset.reason);if(r.isConfirmed){const f=document.getElementById('reasonEditForm');f.action=`{{ route('admin.rejection-reasons.update',':id') }}`.replace(':id',b.dataset.id);f.reason.value=r.value.trim();f.submit();}}));
document.querySelectorAll('.delete-reason').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();const r=await Swal.fire({title:'Disable this reason?',text:'It will no longer appear while rejecting new listings.',icon:'warning',showCancelButton:true,confirmButtonText:'Yes, disable',confirmButtonColor:'#dc2626'});if(r.isConfirmed)f.submit();}));
</script>@endpush
