@extends('layouts.admin')
@section('title','Admin Dashboard')
@push('styles')<style>.dash-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.dash-two{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}@media(max-width:850px){.dash-two{grid-template-columns:1fr}}</style>@endpush
@section('admin-content')
<div class="space-y-5 p-5 lg:p-6">
    <header><p class="text-[10px] font-extrabold uppercase tracking-[.2em] text-indigo-600">Your workspace</p><h1 class="mt-1 text-2xl font-extrabold text-slate-900">Good {{ now()->hour<12?'morning':(now()->hour<17?'afternoon':'evening') }}, {{ Auth::user()->name }}</h1><p class="text-sm text-slate-500">Only the modules assigned to your role are shown here.</p></header>

    <section class="dash-grid">
        @if($access['listings'])
            @foreach([['Active listings',$activeRooms,'fa-building-circle-check','emerald'],['Pending review',$pendingRooms,'fa-clock','amber'],['Approved listings',$approvedRooms,'fa-circle-check','blue']] as [$label,$value,$icon,$tone])<article class="rounded-2xl border bg-white p-4 shadow-sm"><div class="flex justify-between"><div><p class="text-[10px] font-bold uppercase text-slate-400">{{ $label }}</p><p class="mt-2 text-2xl font-extrabold">{{ $value }}</p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-{{ $tone }}-50 text-{{ $tone }}-600"><i class="fas {{ $icon }}"></i></span></div></article>@endforeach
        @endif
        @if($access['people'])<article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Users & owners</p><p class="mt-2 text-2xl font-extrabold">{{ $users }} <small class="text-xs text-slate-400">users</small></p><p class="text-xs text-slate-500">{{ $owners }} property owners</p></article>@endif
        @if($access['support'])<article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Support desk</p><p class="mt-2 text-2xl font-extrabold">{{ $openComplaints }} <small class="text-xs text-slate-400">open</small></p><p class="text-xs text-slate-500">{{ $unreadContacts }} unread enquiries</p></article>@endif
        @if($access['finance'])<article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Platform revenue</p><p class="mt-2 text-2xl font-extrabold">₹{{ number_format($totalEarnings) }}</p><p class="text-xs text-slate-500">₹{{ number_format($todayEarnings) }} collected today</p></article>@endif
        @if($access['content'])<article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Website content</p><p class="mt-2 text-2xl font-extrabold">{{ $contentStats['blogs'] }} <small class="text-xs text-slate-400">blogs</small></p><p class="text-xs text-slate-500">{{ $contentStats['offers'] }} offers · {{ $contentStats['pages'] }} pages</p></article>@endif
        @if($access['reports'])<article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Activity today</p><p class="mt-2 text-2xl font-extrabold">{{ $reportStats['searches_today'] }} <small class="text-xs text-slate-400">searches</small></p><p class="text-xs text-slate-500">{{ $reportStats['unlocks_today'] }} contact unlocks</p></article>@endif
    </section>

    @if(count($quickLinks))<section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="text-sm font-extrabold">Your work tools</h2><p class="text-xs text-slate-500">Shortcuts allowed by your role</p><div class="mt-4 dash-grid">@foreach($quickLinks as $link)<a href="{{ $link['route'] }}" class="flex items-center gap-3 rounded-xl border p-3 text-xs font-bold text-slate-700 hover:border-indigo-200 hover:bg-indigo-50"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-100 text-indigo-600"><i class="fas {{ $link['icon'] }}"></i></span>{{ $link['label'] }}<i class="fas fa-arrow-right ml-auto text-[9px] text-slate-300"></i></a>@endforeach</div></section>@endif

    @if(count($actionQueues))<section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex justify-between"><div><h2 class="text-sm font-extrabold">Action required</h2><p class="text-xs text-slate-500">Queues available to your role</p></div><span class="rounded-full bg-red-50 px-2.5 py-1 text-[10px] font-bold text-red-700">{{ collect($actionQueues)->sum('count') }} pending</span></div><div class="mt-4 dash-grid">@foreach($actionQueues as $queue)<a href="{{ $queue['route'] }}" class="flex items-center gap-3 rounded-xl border p-3 hover:bg-slate-50"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600"><i class="fas {{ $queue['icon'] }}"></i></span><span class="min-w-0 flex-1 text-xs font-semibold text-slate-600">{{ $queue['label'] }}</span><strong>{{ $queue['count'] }}</strong></a>@endforeach</div></section>@endif

    @if($access['finance'])<section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex justify-between"><div><h2 class="text-sm font-extrabold">Monthly platform revenue</h2><p class="text-xs text-slate-500">Collections in {{ now()->year }}</p></div><a href="{{ route('admin.payments.index') }}" class="text-xs font-bold text-indigo-600">View payments</a></div><div class="mt-4 h-[280px]"><canvas id="revenueChart"></canvas></div></section>@endif

    <section class="dash-two">
        @if($access['people'])@foreach([['Recent users',$recentUsers,'admin.users','fa-user'],['Recent owners',$recentOwners,'admin.owners','fa-user-tie']] as [$heading,$records,$route,$icon])<div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">{{ $heading }}</h2><a href="{{ route($route) }}" class="text-xs font-bold text-indigo-600">View all</a></div><div class="mt-3 divide-y">@forelse($records as $record)<a href="{{ $route==='admin.owners'?route('admin.owners.detail',$record):route('admin.users.detail',$record) }}" class="flex items-center gap-3 py-3"><i class="fas {{ $icon }} text-indigo-500"></i><span class="min-w-0 flex-1 truncate text-xs font-bold">{{ $record->name }}</span></a>@empty<p class="py-5 text-xs text-slate-400">No records.</p>@endforelse</div></div>@endforeach @endif
        @if($access['listings'])<div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">Recent listings</h2><a href="{{ route('admin.all-rooms') }}" class="text-xs font-bold text-indigo-600">View all</a></div><div class="mt-3 divide-y">@forelse($recentRooms as $room)<a href="{{ route('admin.rooms.show',$room) }}" class="flex items-center gap-3 py-3"><span class="h-7 w-1 rounded bg-indigo-500"></span><span class="min-w-0 flex-1"><strong class="block truncate text-xs">{{ $room->title??'Room #'.$room->id }}</strong><small class="text-[10px] text-slate-400">{{ $room->owner?->name??'Owner unavailable' }}</small></span></a>@empty<p class="py-5 text-xs text-slate-400">No listings.</p>@endforelse</div></div>@endif
        @if($access['support'])<div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">Recent support tickets</h2><a href="{{ route('admin.complaints.index') }}" class="text-xs font-bold text-indigo-600">View all</a></div><div class="mt-3 divide-y">@forelse($recentComplaints as $ticket)<a href="{{ route('admin.complaints.show',$ticket) }}" class="flex items-center gap-3 py-3"><span class="rounded-lg bg-red-50 px-2 py-1 text-[9px] font-bold uppercase text-red-600">{{ $ticket->priority }}</span><span class="min-w-0 flex-1"><strong class="block truncate text-xs">{{ $ticket->subject }}</strong><small class="text-[10px] text-slate-400">{{ $ticket->ticket_number }} · {{ str_replace('_',' ',$ticket->status) }}</small></span></a>@empty<p class="py-5 text-xs text-slate-400">No support tickets.</p>@endforelse</div></div>@endif
    </section>

    @if($access['finance'])<section class="overflow-hidden rounded-2xl border bg-white"><div class="flex justify-between border-b px-5 py-4"><div><h2 class="text-sm font-extrabold">Recent payments</h2><p class="text-xs text-slate-500">Latest financial activity</p></div><a href="{{ route('admin.payments.index') }}" class="text-xs font-bold text-indigo-600">View all</a></div><div class="overflow-x-auto"><table class="w-full min-w-[620px]"><thead><tr><th>User</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody class="divide-y">@forelse($recentPayments as $payment)<tr><td class="px-5 text-xs font-bold">{{ $payment->user?->name??'Deleted user' }}</td><td class="px-5 text-xs capitalize">{{ $payment->type }}</td><td class="px-5 text-xs font-extrabold">₹{{ number_format($payment->amount) }}</td><td class="px-5 text-xs capitalize">{{ $payment->status }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-xs text-slate-400">No payments.</td></tr>@endforelse</tbody></table></div></section>@endif

    @if(!collect($access)->contains(true))<section class="rounded-2xl border border-dashed bg-white p-10 text-center"><i class="fas fa-user-lock text-3xl text-slate-300"></i><h2 class="mt-3 text-base font-extrabold">No workspace modules assigned</h2><p class="mt-1 text-xs text-slate-500">Ask the Super Admin to update your role permissions.</p></section>@endif
</div>
@endsection
@if($access['finance'])@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>const ctx=document.getElementById('revenueChart');if(ctx&&window.Chart)new Chart(ctx,{type:'line',data:{labels:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],datasets:[{data:@json($revenueData),borderColor:'#4f46e5',backgroundColor:'rgba(79,70,229,.09)',fill:true,tension:.38}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});</script>@endpush @endif
