<?php $__env->startSection('title','Admin Dashboard'); ?>
<?php $__env->startPush('styles'); ?>
<link rel="stylesheet" href="<?php echo e(asset('css/admin-shared.css')); ?>">
    <link rel="stylesheet" href="<?php echo e(asset('css/admin-misc.css')); ?>"><?php $__env->stopPush(); ?>
<?php $__env->startSection('admin-content'); ?>
<div class="space-y-5 p-5 lg:p-6">
    <header><p class="text-[10px] font-extrabold uppercase tracking-[.2em] admin-theme-text">Your workspace</p><h1 class="mt-1 text-2xl font-extrabold text-slate-900">Good <?php echo e(now()->hour<12?'morning':(now()->hour<17?'afternoon':'evening')); ?>, <?php echo e(Auth::user()->name); ?></h1><p class="text-sm text-slate-500">Only the modules assigned to your role are shown here.</p></header>

    <section class="dash-grid">
        <?php if($access['listings']): ?>
            <?php $__currentLoopData = [['Active listings',$activeRooms,'fa-building-circle-check','emerald'],['Pending review',$pendingRooms,'fa-clock','amber'],['Approved listings',$approvedRooms,'fa-circle-check','blue']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$label,$value,$icon,$tone]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><article class="rounded-2xl border bg-white p-4 shadow-sm"><div class="flex justify-between"><div><p class="text-[10px] font-bold uppercase text-slate-400"><?php echo e($label); ?></p><p class="mt-2 text-2xl font-extrabold"><?php echo e($value); ?></p></div><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-<?php echo e($tone); ?>-50 text-<?php echo e($tone); ?>-600"><i class="fas <?php echo e($icon); ?>"></i></span></div></article><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
        <?php endif; ?>
        <?php if($access['people']): ?><article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Users & owners</p><p class="mt-2 text-2xl font-extrabold"><?php echo e($users); ?> <small class="text-xs text-slate-400">users</small></p><p class="text-xs text-slate-500"><?php echo e($owners); ?> property owners</p></article><?php endif; ?>
        <?php if($access['brokers']): ?><article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Brokers</p><p class="mt-2 text-2xl font-extrabold"><?php echo e($brokers); ?> <small class="text-xs text-slate-400">total</small></p><p class="text-xs text-slate-500"><?php echo e($approvedBrokers); ?> approved · <?php echo e($pendingBrokers); ?> pending</p></article><?php endif; ?>
        <?php if($access['support']): ?><article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Support desk</p><p class="mt-2 text-2xl font-extrabold"><?php echo e($openComplaints); ?> <small class="text-xs text-slate-400">open</small></p><p class="text-xs text-slate-500"><?php echo e($unreadContacts); ?> unread enquiries</p></article><?php endif; ?>
        <?php if($access['finance']): ?><article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Platform revenue</p><p class="mt-2 text-2xl font-extrabold">₹<?php echo e(number_format($totalEarnings)); ?></p><p class="text-xs text-slate-500">₹<?php echo e(number_format($todayEarnings)); ?> collected today</p></article><?php endif; ?>
        <?php if($access['content']): ?><article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Website content</p><p class="mt-2 text-2xl font-extrabold"><?php echo e($contentStats['blogs']); ?> <small class="text-xs text-slate-400">blogs</small></p><p class="text-xs text-slate-500"><?php echo e($contentStats['offers']); ?> offers · <?php echo e($contentStats['pages']); ?> pages</p><p class="text-xs text-slate-500"><?php echo e($contentStats['home_features']); ?> why choose · <?php echo e($contentStats['how_it_works']); ?> steps · <?php echo e($contentStats['testimonials']); ?> reviews</p></article><?php endif; ?>
        <?php if($access['reports']): ?><article class="rounded-2xl border bg-white p-4 shadow-sm"><p class="text-[10px] font-bold uppercase text-slate-400">Activity today</p><p class="mt-2 text-2xl font-extrabold"><?php echo e($reportStats['searches_today']); ?> <small class="text-xs text-slate-400">searches</small></p><p class="text-xs text-slate-500"><?php echo e($reportStats['unlocks_today']); ?> contact unlocks</p></article><?php endif; ?>
    </section>

    <?php if(count($actionQueues)): ?><section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex justify-between"><div><h2 class="text-sm font-extrabold">Action required</h2><p class="text-xs text-slate-500">Queues available to your role</p></div><span class="rounded-full bg-red-50 px-2.5 py-1 text-[10px] font-bold text-red-700"><?php echo e(collect($actionQueues)->sum('count')); ?> pending</span></div><div class="mt-4 dash-grid"><?php $__currentLoopData = $actionQueues; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $queue): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a href="<?php echo e($queue['route']); ?>" class="flex items-center gap-3 rounded-xl border p-3 hover:bg-slate-50"><span class="flex h-9 w-9 items-center justify-center rounded-lg admin-theme-soft"><i class="fas <?php echo e($queue['icon']); ?>"></i></span><span class="min-w-0 flex-1 text-xs font-semibold text-slate-600"><?php echo e($queue['label']); ?></span><strong><?php echo e($queue['count']); ?></strong></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></section><?php endif; ?>

    <?php if($access['finance']): ?><section class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex justify-between"><div><h2 class="text-sm font-extrabold">Monthly platform revenue</h2><p class="text-xs text-slate-500">Collections in <?php echo e(now()->year); ?></p></div><a href="<?php echo e(route('admin.payments.index')); ?>" class="text-xs font-bold admin-theme-text">View payments</a></div><div class="mt-4 h-[280px]"><canvas id="revenueChart"></canvas></div></section><?php endif; ?>

    <section class="dash-two">
        <?php if($access['people']): ?><?php $__currentLoopData = [['Recent users',$recentUsers,'admin.users','fa-user'],['Recent owners',$recentOwners,'admin.owners','fa-user-tie']]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$heading,$records,$route,$icon]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold"><?php echo e($heading); ?></h2><a href="<?php echo e(route($route)); ?>" class="text-xs font-bold admin-theme-text">View all</a></div><div class="mt-3 divide-y"><?php $__empty_1 = true; $__currentLoopData = $records; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $record): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e($route==='admin.owners'?route('admin.owners.detail',$record):route('admin.users.detail',$record)); ?>" class="flex items-center gap-3 py-3"><i class="fas <?php echo e($icon); ?> admin-theme-text"></i><span class="min-w-0 flex-1 truncate text-xs font-bold"><?php echo e($record->name); ?></span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-5 text-xs text-slate-400">No records.</p><?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php endif; ?>
        <?php if($access['brokers']): ?><div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">Recent brokers</h2><a href="<?php echo e(route('admin.brokers.index')); ?>" class="text-xs font-bold admin-theme-text">View all</a></div><div class="mt-3 divide-y"><?php $__empty_1 = true; $__currentLoopData = $recentBrokers ?? []; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $broker): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e(route('admin.brokers.show', $broker)); ?>" class="flex items-center gap-3 py-3"><i class="fas fa-handshake admin-theme-text"></i><span class="min-w-0 flex-1 truncate text-xs font-bold"><?php echo e($broker->name); ?></span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-5 text-xs text-slate-400">No brokers yet.</p><?php endif; ?></div></div><?php endif; ?>
        <?php if($access['listings']): ?><div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">Recent listings</h2><a href="<?php echo e(route('admin.all-rooms')); ?>" class="text-xs font-bold admin-theme-text">View all</a></div><div class="mt-3 divide-y"><?php $__empty_1 = true; $__currentLoopData = $recentRooms; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $room): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e(route('admin.rooms.show',$room)); ?>" class="flex items-center gap-3 py-3"><span class="h-7 w-1 rounded admin-theme-bg"></span><span class="min-w-0 flex-1"><strong class="block truncate text-xs"><?php echo e($room->title??'Room #'.$room->id); ?></strong><small class="text-[10px] text-slate-400"><?php echo e($room->owner?->name??'Owner unavailable'); ?></small></span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-5 text-xs text-slate-400">No listings.</p><?php endif; ?></div></div><?php endif; ?>
        <?php if($access['support']): ?><div class="rounded-2xl border bg-white p-5"><div class="flex justify-between"><h2 class="text-sm font-extrabold">Recent support tickets</h2><a href="<?php echo e(route('admin.complaints.index')); ?>" class="text-xs font-bold admin-theme-text">View all</a></div><div class="mt-3 divide-y"><?php $__empty_1 = true; $__currentLoopData = $recentComplaints; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $ticket): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><a href="<?php echo e(route('admin.complaints.show',$ticket)); ?>" class="flex items-center gap-3 py-3"><span class="rounded-lg bg-red-50 px-2 py-1 text-[9px] font-bold uppercase text-red-600"><?php echo e($ticket->priority); ?></span><span class="min-w-0 flex-1"><strong class="block truncate text-xs"><?php echo e($ticket->subject); ?></strong><small class="text-[10px] text-slate-400"><?php echo e($ticket->ticket_number); ?> · <?php echo e(str_replace('_',' ',$ticket->status)); ?></small></span></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="py-5 text-xs text-slate-400">No support tickets.</p><?php endif; ?></div></div><?php endif; ?>
    </section>

    <?php if($access['finance']): ?><section class="overflow-hidden rounded-2xl border bg-white"><div class="flex justify-between border-b px-5 py-4"><div><h2 class="text-sm font-extrabold">Recent payments</h2><p class="text-xs text-slate-500">Latest financial activity</p></div><a href="<?php echo e(route('admin.payments.index')); ?>" class="text-xs font-bold admin-theme-text">View all</a></div><div class="overflow-x-auto"><table class="w-full min-w-[620px]"><thead><tr><th>User</th><th>Type</th><th>Amount</th><th>Status</th></tr></thead><tbody class="divide-y"><?php $__empty_1 = true; $__currentLoopData = $recentPayments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $payment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="px-5 text-xs font-bold"><?php echo e($payment->user?->name??'Deleted user'); ?></td><td class="px-5 text-xs capitalize"><?php echo e($payment->type); ?></td><td class="px-5 text-xs font-extrabold">₹<?php echo e(number_format($payment->amount)); ?></td><td class="px-5 text-xs capitalize"><?php echo e($payment->status); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4" class="p-8 text-center text-xs text-slate-400">No payments.</td></tr><?php endif; ?></tbody></table></div></section><?php endif; ?>

    <?php if(!collect($access)->contains(true)): ?><section class="rounded-2xl border border-dashed bg-white p-10 text-center"><i class="fas fa-user-lock text-3xl text-slate-300"></i><h2 class="mt-3 text-base font-extrabold">No workspace modules assigned</h2><p class="mt-1 text-xs text-slate-500">Ask the Super Admin to update your role permissions.</p></section><?php endif; ?>
</div>
<?php $__env->stopSection(); ?>
<?php if($access['finance']): ?><?php $__env->startPush('scripts'); ?><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>const ctx=document.getElementById('revenueChart');if(ctx&&window.Chart)new Chart(ctx,{type:'line',data:{labels:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],datasets:[{data:<?php echo json_encode($revenueData, 15, 512) ?>,borderColor:'#4f46e5',backgroundColor:'rgba(79,70,229,.09)',fill:true,tension:.38}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}}});</script><?php $__env->stopPush(); ?> <?php endif; ?>

<?php echo $__env->make('layouts.admin', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\xampp\htdocs\apnanest\resources\views/admin/dashboard.blade.php ENDPATH**/ ?>